version: '3.8'  #version of docker-compose

services: #define containers
  db: #name of the container
    image: postgres:15-alpine #image to use for the container
    environment: #environment variables for the container
      POSTGRES_USER: ${DB_USER} #username for the database
      POSTGRES_PASSWORD: ${DB_PASS} #password for the database
      POSTGRES_DB: ${DB_NAME} #name of the database
    ports:
      - "5432:5432" #map port 5432 of the container to port 5432 of the host machine
    volumes:
      - postgres_data:/var/lib/postgresql/data # Thư mục lưu dữ liệu của Postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ] # Kiểm tra kết nối đến database
      interval: 10s # Khoảng thời gian giữa các lần kiểm tra
      timeout: 5s # Thời gian chờ trước khi kết luận container không khỏe
      retries: 5 # Số lần thử lại trước khi kết luận container không khỏe

  cache:
    image: redis:alpine #image to use for the container
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379" #map port 6379 of the container to port 6379 of the host machine
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5


  backend:
    build: . #build the image from the Dockerfile in the current directory
    image: ngphthinh/shop-vibe:1.0.0
    ports:
      - "8080:8080"  #map port 8080 of the container to port 8080 of the host machine
    env_file: .env #load environment variables from the .env file
    depends_on:
      db: { condition: service_healthy } #wait for the db container to be healthy before starting the backend container
      cache: { condition: service_healthy } #wait for the cache container to be healthy before starting the backend container

volumes: #define volumes
  postgres_data: #name of the volume